server:
  port: 8081

spring:
  application:
    name: address
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

address:
  db:
    path: D:/work_space/address/data/address.db
#    path: D:/work_space/address/data/rnaddrkor_address.db
#  data:
#    path: D:/work_space/data

logging:
  level:
    com.address: DEBUG
