server:
  port: 8081

spring:
  application:
    name: address
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

address:
  db:
    path: # SQLite DB 파일 경로 (예: C:/data/address.db)
